apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-folder-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
