apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: default
  labels:
    role: nfs
spec:
  volumes:
      - name: nfs-share-folder
        persistentVolumeClaim:
          claimName: nfs-share-folder-claim
  restartPolicy: Never
  containers:
      - image: itsthenetwork/nfs-server-alpine
        imagePullPolicy: IfNotPresent
        name: nfs-server
        volumeMounts:
            - name: nfs-share-folder
              mountPath: /share
        securityContext:
            privileged: true
        env:
            - name: SHARED_DIRECTORY
              value: "/share"
           #- name: READ_ONLY
           #  value: ""
            - name: SYNC
              value: ""
        securityContext:
            privileged: true
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs
  # NFS volume does not support DNS, so choosing a IP
  # for Magnum
  clusterIP: 10.254.204.67
  # for Kubespray
  # clusterIP: 10.233.46.63
  ports:
    # Open the ports required by the NFS server
    - name: tcp-2049
      port: 2049
      protocol: TCP
