apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: default
  labels:
    role: nfs
spec:
  volumes:
      - name: nfs-share-folder
        persistentVolumeClaim:
          claimName: nfs-share-folder-claim
  restartPolicy: Never
  containers:
      - image: itsthenetwork/nfs-server-alpine
        imagePullPolicy: IfNotPresent
        name: nfs-server
        volumeMounts:
            - name: nfs-share-folder
              mountPath: /share
        securityContext:
            privileged: true
        env:
            - name: SHARED_DIRECTORY
              value: "/share"
           #- name: READ_ONLY
           #  value: ""
            - name: SYNC
              value: ""
        securityContext:
            privileged: true
